{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
data:
  database.yml.erb: |
    production:
      adapter: postgresql
      encoding: unicode
      database: {{ template "gitlab.psql.database" . }}
      pool: 10
      username: {{ template "gitlab.psql.username" . }}
      password: <%= File.read("/etc/gitlab/postgres/psql-password") %>
      host: {{ template "gitlab.psql.host" . }}
      port: {{ template "gitlab.psql.port" . }}
      # load_balancing:
      #   hosts:
      #     - host1.example.com
      #     - host2.example.com
  resque.yml.erb: |
    production:
      # Redis (single instance)
      url: redis://:<%= File.read("/etc/gitlab/redis/password") %>@{{ template "gitlab.redis.host" . }}:{{ template "gitlab.redis.port" . }}
  gitlab.yml: |
    production: &base
      gitlab:
      repositories:
        storages:
          default:
            path: /var/opt/gitlab/repo
            gitaly_address: tcp://localhost:8075
  configure: |
    set -e
    mkdir -p /init-secrets/redis /init-secrets/postgres /init-secrets/rails-secrets /init-secrets/migrations
    cp /init-config/redis/password  /init-secrets/redis/password
    cp /init-config/postgres/psql-password  /init-secrets/postgres/psql-password
    cp /init-config/rails-secrets/secrets.yml /init-secrets/rails-secrets/secrets.yml
    cp /init-config/migrations/initial_root_password /init-secrets/migrations/initial_root_password
{{- if .Values.global.operator.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-migrations-jobspec
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
data:
  template: |-
{{ include (print $.Template.BasePath "/_jobspec.yaml") . | indent 4 }}
{{- end }}
# Leave this here - This line denotes end of block to the parser.
{{- end }}
