{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-ingress.controller.fullname" . }}
  namespace: {{ $.Release.Namespace }}
{{- if .Values.controller.service.annotations }}
  annotations:
{{ toYaml .Values.controller.service.annotations | indent 4 }}
{{- end }}
  labels:
{{- if .Values.controller.service.labels }}
{{ toYaml .Values.controller.service.labels | indent 4 }}
{{- end }}
    component: "{{ .Values.controller.name }}"
{{ include "gitlab.standardLabels" . | indent 4 }}
spec:
  clusterIP: "{{ .Values.controller.service.clusterIP }}"
{{- if .Values.controller.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.controller.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.global.hosts.externalIP }}
  loadBalancerIP: "{{ .Values.global.hosts.externalIP }}"
{{- end }}
{{- if .Values.controller.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.controller.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.controller.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.controller.service.externalTrafficPolicy }}"
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.controller.service.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.controller.service.healthCheckNodePort }}
{{- end }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.controller.service.targetPorts.http }}
      {{- if (and (eq .Values.controller.service.type "NodePort") (not (empty .Values.controller.service.nodePorts.http))) }}
      nodePort: {{ .Values.controller.service.nodePorts.http }}
      {{- end }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.controller.service.targetPorts.https }}
      {{- if (and (eq .Values.controller.service.type "NodePort") (not (empty .Values.controller.service.nodePorts.https))) }}
      nodePort: {{ .Values.controller.service.nodePorts.https }}
      {{- end }}
    - name: gitlab-shell-tcp
      port: {{ include "gitlab.shell.port" $ | int }}
      protocol: TCP
      targetPort: gitlab-shell-tcp
  {{- range $key, $value := .Values.tcp }}
    - name: "{{ $key }}-tcp"
      port: {{ $key }}
      protocol: TCP
      targetPort: "{{ $key }}-tcp"
  {{- end }}
  {{- range $key, $value := .Values.udp }}
    - name: "{{ $key }}-udp"
      port: {{ $key }}
      protocol: UDP
      targetPort: "{{ $key }}-udp"
  {{- end }}
  selector:
    app: {{ template "name" . }}
    component: "{{ .Values.controller.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.controller.service.type }}"
{{- end }}
