#!/bin/bash

set -e

KUBE_COMMAND=$(which kubectl)

OPTS=`getopt -o n: --long namespace:,shell-name:,shell-key:,gitaly-name:,gitaly-key: -n 'create-secret-tokens' -- "$@"`
eval set -- "$OPTS"

NAMESPACE="default"
SHELL_SECRET_NAME="gitlab-shell-secret"
SHELL_SECRET_KEY="secret"
GITALY_SECRET_NAME="gitaly-secret"
GITALY_SECRET_KEY="token"

while [ ! $# -eq 0 ]
do
	case "$1" in
		--namespace | -n ) NAMESPACE="$2"; shift ;;
		--shell-name ) SHELL_SECRET_NAME="$2"; shift ;;
		--shell-key ) SHELL_SECRET_KEY="$2"; shift ;;
		--gitaly-name ) GITALY_SECRET_NAME="$2"; shift ;;
		--gitaly-key ) GITALY_SECRET_KEY="$2"; shift ;;
	esac
	shift
done

# Create shell secret token if it doesn't exist
if ! $KUBE_COMMAND -n ${NAMESPACE} get secret ${SHELL_SECRET_NAME} > /dev/null 2>&1; then
  $KUBE_COMMAND -n ${NAMESPACE} create secret generic ${SHELL_SECRET_NAME} --from-literal=${SHELL_SECRET_KEY}=$(head -c 512 /dev/urandom | tr -cd 'a-zA-Z0-9' | head -c 64)
fi

# Create gitaly secret token if it doesn't exist
if ! $KUBE_COMMAND -n ${NAMESPACE} get secret ${GITALY_SECRET_NAME} > /dev/null 2>&1; then
 $KUBE_COMMAND -n ${NAMESPACE} create secret generic ${GITALY_SECRET_NAME} --from-literal=${GITALY_SECRET_KEY}=$(head -c 512 /dev/urandom | tr -cd 'a-zA-Z0-9' | head -c 64)
fi
