{{- if and .Values.enabled .Values.rbac.create (not .Values.global.operatorenabled) -}}
{{ include (print $.Template.BasePath "/_rbac-serviceaccount.yaml") . }}
---
{{ include (print $.Template.BasePath "/_rbac-role.yaml") . }}
---
{{ include (print $.Template.BasePath "/_rbac-rolebinding.yaml") . }}
{{- end}}
